apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: middleware
spec:
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200                    
  selector:
    app.kubernetes.io/name: elasticsearch
