---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: middleware
  labels:
    app: kibana
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch-0.elasticsearch:9200","http://elasticsearch-1.elasticsearch:9200","http://elasticsearch-2.elasticsearch:9200" ]
    elasticsearch.username: "kibana"
    elasticsearch.password: "test@123,"
    i18n.locale: "zh-CN"
    kibana.index: ".kibana"
