apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-cluster
  name: es-cluster
  namespace: middleware
spec:
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200                    
  selector:
    app: es-cluster
