apiVersion: v1
kind: Secret
metadata:
  name: milvus-s3-secret
  namespace: middleware
type: Opaque
stringData:
  accesskey: bEDleifnvXDjKqXfqU5P
  secretkey: yiR0vnPni9xHEGhCWskc9RXf8VPUmSnyel40nj2Y 
