---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-server
  namespace: middleware
spec:
  secretName: etcd-server-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: etcd
  duration: 87600h
  renewBefore: 360h
  dnsNames:
  - etcd
  - etcd.middleware
  - etcd.middleware.svc.cluster.local
  - etcd-0
  - etcd-0.etcd
  - etcd-0.etcd.middleware
  - etcd-0.etcd.middleware.svc
  - etcd-0.etcd.middleware.svc.cluster.local
  - etcd-1
  - etcd-1.etcd
  - etcd-1.etcd.middleware
  - etcd-1.etcd.middleware.svc
  - etcd-1.etcd.middleware.svc.cluster.local
  - etcd-2
  - etcd-2.etcd
  - etcd-2.etcd.middleware
  - etcd-2.etcd.middleware.svc
  - etcd-2.etcd.middleware.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
  namespace: middleware
spec:
  secretName: etcd-client-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  commonName: etcd
  dnsNames:
  - etcd
  - etcd.middleware
  - etcd.middleware.svc.cluster.local
  - etcd-0
  - etcd-0.etcd
  - etcd-0.etcd.middleware
  - etcd-0.etcd.middleware.svc
  - etcd-0.etcd.middleware.svc.cluster.local
  - etcd-1
  - etcd-1.etcd
  - etcd-1.etcd.middleware
  - etcd-1.etcd.middleware.svc
  - etcd-1.etcd.middleware.svc.cluster.local
  - etcd-2
  - etcd-2.etcd
  - etcd-2.etcd.middleware
  - etcd-2.etcd.middleware.svc
  - etcd-2.etcd.middleware.svc.cluster.local

