apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitor
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      receiver: default
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      group_by: ['alertname','cluster']
      routes:
      #- receiver: 'database'
      #  group_wait: 10s
      #  matchers:
      #  - service=~"mysql|cassandra"
      - receiver: 'default'
        group_wait: 10s
        group_interval: 30s
        group_by: [alertname, namespace]
        matchers:
        - severity =~ "warning|critical"
    receivers:
    - name: 'default'
      webhook_configs:
      - url: http://192.168.1.220:8800/webhook?type=fs&tpl=feishu&split=false&fsurl=https://open.feishu.cn/open-apis/bot/v2/hook/bf8bb912-bc2e-40ad-9533-fcb8068aa621
